/**
 * Northpower.Asset.Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: edge
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssetTemplateProperty } from './assetTemplateProperty';
import { AssetTypeEnum } from './assetTypeEnum';


export interface AssetTemplate { 
    id: string;
    assetType: AssetTypeEnum;
    assetTypeMapping?: string;
    properties?: Array<AssetTemplateProperty>;
}
