/**
 * Northpower.Asset.Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: edge
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type AssetTypeEnum = 0 | 1 | 2;

export const AssetTypeEnum = {
    NUMBER_0: 0 as AssetTypeEnum,
    NUMBER_1: 1 as AssetTypeEnum,
    NUMBER_2: 2 as AssetTypeEnum
};
