/**
 * Northpower.Asset.Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: edge
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type DataTypeEnum = 0 | 1 | 2 | 3 | 4;

export const DataTypeEnum = {
    NUMBER_0: 0 as DataTypeEnum,
    NUMBER_1: 1 as DataTypeEnum,
    NUMBER_2: 2 as DataTypeEnum,
    NUMBER_3: 3 as DataTypeEnum,
    NUMBER_4: 4 as DataTypeEnum
};
